# this dockerfile's purpose is to use terraform in the localstack container...
FROM localstack/localstack:latest

RUN apt-get update && apt-get install -y curl unzip \
    && curl -O https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip \
    && unzip terraform_1.7.0_linux_amd64.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform_1.7.0_linux_amd64.zip